name: Data Collection and Storage

on:
  schedule:
    - cron: '*/5 8-23 * * *'

jobs:
  collect-and-store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install R and required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base r-cran-dbi r-cran-dplyr r-cran-rpostgres
          R -e "install.packages(c('DBI', 'dplyr', 'RPostgres'))"

      - name: Run R script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          Rscript 
          source("R/disneydata.R")
        shell: Rscript {0}
